-- Скрипт создания роли суперпользователя
-- by Nikolai Krasilnikov
-- This file is distributed under Apache License 2.0 (01.2004).
--   http://www.apache.org/licenses/
-- create 24.09.2010
-- update 03.06.2012 08.07.2015 24.12.2015 15.08.2016
--*****************************************************************************
--
declare
  tmpVar NUMBER;
begin
  select count(*)into tmpVar from dual where exists 
  (select * from DBA_ROLES where ROLE='PROG_ROLE');
  if tmpVar!=0 then 
    execute immediate('
      DROP ROLE "PROG_ROLE" 
    ');
  end if;
end;
/
CREATE ROLE "PROG_ROLE" NOT IDENTIFIED;
GRANT ALTER ANY INDEX TO PROG_ROLE;
GRANT ALTER ANY PROCEDURE TO PROG_ROLE;
GRANT ALTER ANY TABLE TO PROG_ROLE;
GRANT ALTER ANY TRIGGER TO PROG_ROLE;
GRANT COMMENT ANY TABLE TO PROG_ROLE;
GRANT CREATE ANY INDEX TO PROG_ROLE;
GRANT CREATE ANY PROCEDURE TO PROG_ROLE;
GRANT CREATE ANY SYNONYM TO PROG_ROLE;
GRANT CREATE ANY TABLE TO PROG_ROLE;
GRANT CREATE ANY TRIGGER TO PROG_ROLE;
GRANT CREATE ANY VIEW TO PROG_ROLE;
GRANT CREATE PROCEDURE TO PROG_ROLE;
GRANT CREATE PUBLIC SYNONYM TO PROG_ROLE;
GRANT CREATE SYNONYM TO PROG_ROLE;
GRANT CREATE TABLE TO PROG_ROLE;
GRANT CREATE TRIGGER TO PROG_ROLE;
GRANT CREATE VIEW TO PROG_ROLE;
GRANT DELETE ANY TABLE TO PROG_ROLE;
GRANT DROP ANY INDEX TO PROG_ROLE;
GRANT DROP ANY PROCEDURE TO PROG_ROLE;
GRANT DROP ANY SYNONYM TO PROG_ROLE;
GRANT DROP ANY TABLE TO PROG_ROLE;
GRANT DROP ANY TRIGGER TO PROG_ROLE;
GRANT DROP ANY VIEW TO PROG_ROLE;
GRANT DROP PUBLIC SYNONYM TO PROG_ROLE;
GRANT EXECUTE ANY PROCEDURE TO PROG_ROLE;
GRANT FORCE ANY TRANSACTION TO PROG_ROLE;
GRANT FORCE TRANSACTION TO PROG_ROLE;
GRANT INSERT ANY TABLE TO PROG_ROLE;
GRANT LOCK ANY TABLE TO PROG_ROLE;
GRANT SELECT ANY TABLE TO PROG_ROLE;
GRANT UPDATE ANY TABLE TO PROG_ROLE;
GRANT CREATE SESSION TO PROG_ROLE;
GRANT CREATE ANY SEQUENCE TO PROG_ROLE;
GRANT GRANT ANY OBJECT PRIVILEGE TO PROG_ROLE;
GRANT CREATE ANY TYPE TO PROG_ROLE;
GRANT EXECUTE ANY TYPE TO PROG_ROLE;
GRANT ADMINISTER DATABASE TRIGGER TO PROG_ROLE;
grant debug any procedure to PROG_ROLE; 
grant debug connect session to PROG_ROLE; 

