SELECT owner, segment_name, segment_type, segment_type 
FROM dba_segments 
WHERE owner NOT IN ('SYS', 'SYSTEM','OUTLN') 
AND tablespace_name = 'SYSTEM'

;
ALTER TABLE ... MOVE TABLESPACE
;
ALTER INDEX ... REBUILD TABLESPACE ..

ALTER DATABASE DEFAULT TABLESPACE USERS;

SELECT PROPERTY_VALUE
  FROM DATABASE_PROPERTIES
  WHERE PROPERTY_NAME = 'DEFAULT_PERMANENT_TABLESPACE';
  
ALTER DATABASE DEFAULT TEMPORARY TABLESPACE temp;  
  
SELECT PROPERTY_VALUE
FROM DATABASE_PROPERTIES
WHERE PROPERTY_NAME = 'DEFAULT_TEMP_TABLESPACE';  

CREATE TABLESPACE SP_FILES DATAFILE 
  'SP_FILES' SIZE 2G REUSE AUTOEXTEND ON NEXT 1G MAXSIZE UNLIMITED;


